---
application:
  scheme: https
  domain: api.wormhole.im

db:
  type: sqlite3
  connection: data/db.sqlite

integration:
  register: 30
  url_content_comment_vote:
    like: 3
    hate: -3

http:
  server:
    host: 127.0.0.1
    port: 8080

cache:
  type: redis
  host: 127.0.0.1
  port: 5000
  password: PrimasGoGoGo

oauth:
  google:
    client_id:
    client_secret:

admin:
  key:

cors:
  origins:
   - "*"
  methods:
   - "GET"
   - "POST"
   - "PUT"
   - "DELETE"
  allowed_headers:
   - "Authorization"
   - "Origin"
   - "Content-Type"
   - "Content-Length"
  allow_credentials: true

recaptcha:
  secret:
