---
db:
  type: sqlite3

http:
  server:
    host: 127.0.0.1
    port: 8080

integration:
  register: 30
  url_content_comment_vote:
    like: 3
    hate: -3

cache:
  type: memory

admin:
  key: test_key

cors:
  origins:
    - "*"
  methods:
    - GET
    - POST
    - PUT
    - DELETE
  allowed_headers:
    - "Authorization"
    - "Origin"
  exposed_headers:
  allow_credentials: true
